---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aws-keys
  namespace: mld
spec:
  itemPath: "vaults/kubernetes/items/aws-keys"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mld-db-superuser
  namespace: mld
spec:
  itemPath: "vaults/kubernetes/items/mld-db-superuser"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mld-db-user
  namespace: mld
spec:
  itemPath: "vaults/kubernetes/items/mld-db-user"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backend-secrets
  namespace: mld
spec:
  itemPath: "vaults/kubernetes/items/mld-backend"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: frontend-secrets
  namespace: mld
spec:
  itemPath: "vaults/kubernetes/items/mld-frontend"
