---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mld
  namespace: mld
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/generic
      sourceRef:
        kind: GitRepository
        name: jf-helm
      interval: 1m0s
  values:
    backend:
      enabled: false
    frontend:
      enabled: true
      image:
        repository: joeyfreeland/mldfe
        tag: 1.0.4
      env:
        - name: NODE_ENV
          value: "production"
        - name: NEXTAUTH_URL
          value: "https://mldegrees.com"
        - name: NEXT_PUBLIC_API_URL
          value: "https://mldegrees.com"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: google-client-secret
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: auth-secret
    ingress:
      enabled: true
      className: "cloudflare-tunnel-f6d"
      annotations: {}
      hosts:
        - host: mldegrees.com
        - host: www.mldegrees.com
        - host: machinelearningdegrees.com
        - host: www.machinelearningdegrees.com
      paths:
        - path: /api/auth/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: mld-frontend
              port:
                number: 80
        - path: /(api/.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend
              port:
                number: 8080
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: mld-frontend
              port:
                number: 80
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: backend
  namespace: mld
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/temp
      sourceRef:
        kind: GitRepository
        name: jf-helm
      interval: 1m0s
  values:
    fullnameOverride: backend
    replicaCount: 2
    image:
      repository: joeyfreeland/mldbe
      pullPolicy: Always
      tag: 1.0.4
    imagePullSecrets:
      - name: dockerhub
    serviceAccount:
      create: true
    service:
      type: ClusterIP
      port: 8080
    env:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: backend-secrets
            key: database-url
      - name: PORT
        value: "8080"
    livenessProbe:
      path: /api/health
    readinessProbe:
      path: /api/health
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
    autoscaling:
      enabled: true
