# TODO: change all my flux times to a lot slower
---
# TODO: Should really make a proper Helm repository instead of using a
# GitRepository here but this is fine.
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jf-helm
  namespace: mld
spec:
  interval: 1m0s
  url: https://github.com/jfreeland/helm
  ref:
    branch: main
  secretRef:
    name: github
  values:
    backend:
      image:
        tag: v1.0.2
    frontend:
      image:
        tag: v1.0.2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mld
  namespace: mld
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/generic
      sourceRef:
        kind: GitRepository
        name: jf-helm
      interval: 1m0s
  values:
    backend:
      enabled: true
      image:
        repository: joeyfreeland/mldbe
        tag: v1.0.2
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database-url
        - name: PORT
          value: "8080"
    frontend:
      enabled: true
      image:
        repository: joeyfreeland/mldfe
        tag: v1.0.2
      env:
        - name: NODE_ENV
          value: "production"
        - name: NEXTAUTH_URL
          value: "https://mldegrees.com"
        - name: NEXT_PUBLIC_API_URL
          value: "https://mldegrees.com"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: google-client-secret
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: auth-secret
    ingress:
      enabled: true
      className: "cloudflare-tunnel-f6d"
      annotations: {}
      hosts:
        - host: mldegrees.com
        - host: www.mldegrees.com
        - host: machinelearningdegrees.com
        - host: www.machinelearningdegrees.com
      paths:
        - path: /api/auth/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: mld-frontend
              port:
                number: 80
        - path: /(api/.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: mld-backend
              port:
                number: 8080
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: mld-frontend
              port:
                number: 80
