---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mld-api
  namespace: mld
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/ingress
      sourceRef:
        kind: GitRepository
        name: jf-helm
      interval: 1m0s
  values:
    ingress:
      enabled: true
      className: "cloudflare-tunnel"
      annotations: {}
      hosts:
        - host: api.mldegrees.com
      paths:
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend
              port:
                number: 8080
