---
# TODO: I started 404'ing when I migrated the backend to the more generic
# chart.  That shouldn't happen.  Need to look into
# cloudflare-tunnel-ingress-controller.
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mld
  namespace: mld
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/ingress
      sourceRef:
        kind: GitRepository
        name: jf-helm
      interval: 1m0s
  values:
    ingress:
      enabled: true
      className: "cloudflare-tunnel-f6d"
      annotations: {}
      hosts:
        - host: mldegrees.com
        - host: www.mldegrees.com
        - host: machinelearningdegrees.com
        - host: www.machinelearningdegrees.com
      paths:
        - path: /api/auth/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend
              port:
                number: 3000
        - path: /(api/.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend
              port:
                number: 8080
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend
              port:
                number: 3000
