---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: frontend
  namespace: mld
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/generic
      sourceRef:
        kind: GitRepository
        name: jf-helm
      interval: 1m0s
  values:
    fullnameOverride: frontend
    replicaCount: 2
    image:
      repository: joeyfreeland/mldfe
      pullPolicy: Always
      tag: 1.10.3
    imagePullSecrets:
      - name: dockerhub
    serviceAccount:
      create: true
    podAnnotations:
      ad.datadoghq.com/frontend.logs: '[{"source": "nodejs", "service": "frontend"}]'
      ad.datadoghq.com/frontend.check_names: '["openmetrics"]'
      ad.datadoghq.com/frontend.checks: |
        {
          "openmetrics": {
            "init_config": {},
            "instances": [
              {
                "openmetrics_endpoint": "http://%%host%%:3000/api/metrics",
                "namespace": "frontend",
                "metrics": [".*"],
                "histogram_buckets_as_distributions": true
              }
            ]
          }
        }
    service:
      type: ClusterIP
      port: 3000
    env:
      - name: NODE_ENV
        value: "production"
      - name: NEXTAUTH_URL
        value: "https://mldegrees.com"
      - name: NEXT_PUBLIC_API_URL
        value: "https://api.mldegrees.com"
      - name: GOOGLE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: frontend-secrets
            key: google-client-id
      - name: GOOGLE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: frontend-secrets
            key: google-client-secret
      - name: GITHUB_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: frontend-secrets
            key: github-client-id
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: frontend-secrets
            key: github-client-secret
      - name: AUTH_SECRET
        valueFrom:
          secretKeyRef:
            name: frontend-secrets
            key: auth-secret
      - name: DD_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: DD_DOGSTATSD_PORT
        value: "8125"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    autoscaling:
      enabled: true
