apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: mld-rds-backups
  generateName: mld-rds-backups-
spec:
  forProvider:
    locationConstraint: us-east-1
  providerConfigRef:
    name: f6d-playground
