---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mld-db-user
  namespace: mld
spec:
  encryptedData:
    password: AgBWit/MZP+bAgtLaRLAygBciYvtzORecmEFtT7SqFvroLnGftDvJxCYBGTONQBPTarf/T8I87PJ7M+Bcu0Qq8Uq6dcCBU/JXT0O1smIT2V8CcEAySZXDwtVKKJY2koLFPFJiXbstmvmKi17rRrzWetZ4bFEd8HWWehMdMSnDp7KWPXN+0TrSR3IAYymujt87QCPd7gfnFzzCABSyldRTMB4eXxqV2VyfqqsRNce2e8vGsmsCn6imQXdOcPaCqR/JcC/Aq8+K6O11JFk8KbXoHFdZpitfDOcO9vUcvU31Hp8Jq4Td4KIBXBDsuEiPndbjKMQNWIS/D9Dr1ucci4OGiORFMUIdvpwIcFRdH/nvWkhoR9k+bfxZB0poCxMOOmUnDjBPLw3YBGpp68dR2gn6lWC9bLR1UqakAuObXgy6hLURUmqGmrVd6lvUmVRn+ahIEHFH+0lpu+X2Ryu8XhXAW2sZYyt3UT3HszUHNCkg5pCFNiNcDmjiMMI07vlTx6ApmjRz9G4CfUnRR4rvCg9oMlaXM0XkzR8JS2wcsqnEHOh0egbBCY9vZJkGOY7WxOKY5KPjBfyF354VK+VnSAhToEb+jA+fw4lSoFALeWXDGQ5xbpb7XzyRWHfStfAym1tUlLh5tNJUgleFPhIl3WwdwknH90rWOzbVDcR0rit7OpZghRzrJ/9P2KsUxjcr8fG93HsrMa1y1nabg==
    username: AgAO24NF1eq0LTErGZBzQHdfvrBplxH2jPAy2Mf4n/97mvPrIWw5t4MRCNUb9w+jVZnKILMGtOR0jF5zHJboLS6K+aQJLaujVqrzrgwP8h0pO8Aut1bRykfKqdriZR9SGtbKHreoG8i6xpZEa99wJIpMDu1IuXuQwor97FWiZiGRLE4qWlSHwa8KZoAbJ2oGm8OJZEVM5EmvovHvVMEypRjFzUVTO7ImxR+xWCH6ky+KxH5uLKeEY/WPf9FVeJZAp/+E0CUtZOPeCFoos+4zCB0sQL3Mk6PpYNIjBOJv6F5FLo2HoU7tiKTlWgFMmEQNYAnSPK0lR4kSpGujzIWW2VUQ4p9njId4W+nLNzGHOgFj6vik1Cr3vQd7ss1hGN3E3E7OtCW1A0NoyoBNytdiEMdgTeyJP0/CTnXUVYKq/5MiRHMAm+IP/v8aMzWEjv7jfZk3raZlCma0TvS7LtyuSfL+taNHR4lT4Jyk4tMl7DZHjRB8siShWO0oHR90GP9GNgT7VOTJsPSa3pjIhb1SnFBfVS5OI1ivpO9UypuTaOCnjkF1YAsiHgCx9wWGgb52crY+eZEDasyvonzok+NEFDIf/O+IFdx4G1BkbNOD3aKayJieossUKI1YSIgUhrLiqECDaCjGHA102iORiO8776DZZSg30v28X8WaolGKcFW2zwfqY72BOG9fppdqs6UX3qD5SAo=
  template:
    metadata:
      name: mld-db-user
      namespace: mld
