---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: mld
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  endpoints:
    - port: http
      path: /api/metrics
      interval: 60s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - mld
