name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: test backend
        run: |
          cd backend
          go test ./...

      - name: test frontend
        run: |
          cd frontend
          npm ci
          npm run test

      - name: lint frontend
        run: |
          cd frontend
          npm run lint

      - name: typecheck frontend
        run: |
          cd frontend
          npm run typecheck
