name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persistent-credentials: true

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install semantic-release
        run: npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github @semantic-release/git

      - name: semantic release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
        continue-on-error: true

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push backend
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mldbe:${{ steps.semantic.outputs.new_release_version }}

      - name: build and push frontend
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mldfe:${{ steps.semantic.outputs.new_release_version }}

      - name: setup yq
        uses: mikefarah/yq@v4.44.2

      - name: update helmrelease
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          set -ex
          TAG=${{ steps.semantic.outputs.new_release_version }}
          yq -i ".spec.values.backend.image.tag = \"$TAG\"" deploy/base/helmrelease.yaml
          yq -i ".spec.values.frontend.image.tag = \"$TAG\"" deploy/base/helmrelease.yaml

      - name: commit helmrelease
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          set -ex
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deploy/base/helmrelease.yaml
          git commit -m "ci: update helmrelease to ${{ steps.semantic.outputs.new_release_version }}"
          git push
