name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persistent-credentials: true

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install semantic-release
        run: npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github @semantic-release/git

      - name: semantic release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release

      - name: get next version from git tag
        id: version
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0)
          echo "[DEBUG] Next release version: $VERSION"
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push backend
        id: build_be
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mldbe:${{ steps.version.outputs.tag }}

      - name: build and push frontend
        id: build_fe
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mldbe:${{ steps.version.outputs.tag }}
